// packages/react/src/components/badge/index.tsx
import React, { useMemo, useState, useEffect } from 'react';
import type { badgeProps } from './types';
import '@dpzvc3/styles/dist/components/badge.css';

const prefixCls = 'dpzvc3-badge';

const Badge: React.FC<badgeProps> = ({
  type = 'danger',
  size = 'normal',
  dot = false,
  max = 99,
  number,
  children,
}) => {
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    if (dot) {
      setVisible(true);
    } else if (
      number === null ||
      number === undefined ||
      isNaN(Number(number))
    ) {
      setVisible(false);
    } else {
      setVisible(true);
    }
  }, [number, dot]);

  const supClasses = useMemo(() => {
    const arr: string[] = [`${prefixCls}-${type}`];
    if (!dot) arr.push(`${prefixCls}-size-${size}`);
    if (dot) arr.push(`${prefixCls}-dot`);
    return arr.join(' ');
  }, [type, size, dot]);

  const displayCount = useMemo(() => {
    if (dot) return '';
    const num = Number(number);
    return num <= Number(max) ? String(num) : `${max}+`;
  }, [number, max, dot]);

  return (
    <span className={prefixCls}>
      {children}
      {visible && <sup className={supClasses}>{displayCount}</sup>}
    </span>
  );
};

export type { badgeProps } from './types';
export default Badge;

// src/components/badge/badge.vue
<template>
  <span :class="classes">
    <slot />
    <sup
      v-show="visible"
      :class="supClasses"
    >{{ displayCount }}</sup>
  </span>
</template>

<script>
import { computed, ref, watch } from 'vue'

const prefixCls = 'dpzvc3-badge'

export default {
  name: 'Dpzvc3Badge',
  props: {
    type: {
      type: String,
      default: 'danger',
      validator: (val) => ['normal', 'danger', 'warning', 'success'].includes(val)
    },
    size: {
      type: String,
      default: 'normal',
      validator: (val) => ['small', 'normal', 'large'].includes(val)
    },
    dot: {
      type: Boolean,
      default: false
    },
    max: {
      type: [Number, String],
      default: 99
    },
    number: [Number, String]
  },
  setup (props) {
    const visible = ref(true)

    // 监听 number 来控制 visible
    watch(
      () => props.number,
      (val) => {
        if (props.dot) {
          visible.value = true
        } else if (val == null || isNaN(Number(val))) {
          visible.value = false
        } else {
          visible.value = true
        }
      },
      { immediate: true }
    )

    const classes = computed(() => [prefixCls])
    const supClasses = computed(() => [
      `${prefixCls}-${props.type}`,
      {
        [`${prefixCls}-size-${props.size}`]: !props.dot,
        [`${prefixCls}-dot`]: props.dot
      }
    ])

    const displayCount = computed(() => {
      if (props.dot) return ''
      const num = Number(props.number)
      return num <= Number(props.max) ? String(num) : String(props.max) + '+'
    })

    return {
      classes,
      supClasses,
      visible,
      displayCount
    }
  }
}
</script>
