// packages/react/src/components/badge/index.tsx
import React, { useMemo, useState, useEffect } from 'react';
import type { badgeProps } from './types';
import '@dpzvc3/styles/dist/components/badge.css';

const prefixCls = 'dpzvc3-badge';

const Badge: React.FC<badgeProps> = ({
  type = 'danger',
  size = 'normal',
  dot = false,
  max = 99,
  number,
  children,
}) => {
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    if (dot) {
      setVisible(true);
    } else if (
      number === null ||
      number === undefined ||
      isNaN(Number(number))
    ) {
      setVisible(false);
    } else {
      setVisible(true);
    }
  }, [number, dot]);

  const supClasses = useMemo(() => {
    const arr: string[] = [`${prefixCls}-${type}`];
    if (!dot) arr.push(`${prefixCls}-size-${size}`);
    if (dot) arr.push(`${prefixCls}-dot`);
    return arr.join(' ');
  }, [type, size, dot]);

  const displayCount = useMemo(() => {
    if (dot) return '';
    const num = Number(number);
    return num <= Number(max) ? String(num) : `${max}+`;
  }, [number, max, dot]);

  return (
    <span className={prefixCls}>
      {children}
      {visible && <sup className={supClasses}>{displayCount}</sup>}
    </span>
  );
};

export type { badgeProps } from './types';
export default Badge;

// src/components/badge/badge.tsx
import { defineComponent, computed, ref, watch,PropType } from 'vue'

import type { BadgeProps } from './types'
export type { BadgeProps } 

export default defineComponent({
  name: 'Dpzvc3Badge',

  props: {
    type: {
      type: String as PropType<BadgeProps['type']>,
      default: 'danger'
    },
    size: {
      type: String as PropType<BadgeProps['size']>,
      default: 'normal'
    },
    dot: {
      type: Boolean,
      default: false
    },
    max: {
      type: [Number, String],
      default: 99
    },
    number: {
      type: [Number, String]
    }
  },

  setup (props, { slots }) {
    const prefixCls = 'dpzvc3-badge'
    const visible = ref(true)

    watch(
      () => props.number,
      (val) => {
        if (props.dot) {
          visible.value = true
        } else if (val == null || isNaN(Number(val))) {
          visible.value = false
        } else {
          visible.value = true
        }
      },
      { immediate: true }
    )

    const classes = computed(() => [prefixCls])

    const supClasses = computed(() => [
      `${prefixCls}-${props.type}`,
      {
        [`${prefixCls}-size-${props.size}`]: !props.dot,
        [`${prefixCls}-dot`]: props.dot
      }
    ])

    const displayCount = computed(() => {
      if (props.dot) return ''
      const num = Number(props.number)
      return num <= Number(props.max) ? String(num) : `${props.max}+`
    })

    return () => (
      <span class={classes.value}>
        {slots.default?.()}
        {visible.value && (
          <sup class={supClasses.value}>
            {displayCount.value}
          </sup>
        )}
      </span>
    )
//     h('span', { class: classes.value }, [
//   slots.default ? slots.default() : null,
//   visible.value ? h('sup', { class: supClasses.value }, displayCount.value) : null
// ])
  }
})
