// src/components/card/card.tsx
// src/components/card/card.tsx
import { defineComponent, computed, PropType } from 'vue'

// export type CardProps = {
//   width?: string
// }
import type { CardProps  } from './types'
export type { CardProps } 

const prefixCls = 'dpzvc3-card'

export default defineComponent({
  name: 'Dpzvc3Card',
  props: {
    width: { type: String as PropType<string>, default: '100%' }
  },
  setup(props, { slots }) {
    const classes = computed(() => [prefixCls])
    const headerClass = computed(() => [`${prefixCls}-header`, 'dpzvc3-1px-bottom'])
    const contentClass = computed(() => [`${prefixCls}-content`])
    const footerClass = computed(() => [`${prefixCls}-footer`, 'dpzvc3-1px-top'])
    const cardWidth = computed(() => props.width)

    return () => (
      <div class={classes.value} style={{ width: cardWidth.value }}>
        <div class={headerClass.value}>
          {slots.header?.()}
        </div>
        <div class={contentClass.value}>
          {slots.default ? slots.default() : <div class="main" />}
        </div>
        <div class={footerClass.value}>
          {slots.footer?.()}
        </div>
      </div>
    )
  }
})

// packages/react/src/components/card/index.tsx
import React from 'react';
import type { cardProps } from './types';
import '@dpzvc3/styles/dist/components/card.css';

const prefixCls = 'dpzvc3-card';

const Card: React.FC<cardProps> = (props) => {
  const { width = '100%', header, footer, children } = props;

  const classes = [prefixCls].join(' ');
  const headerCls = `${prefixCls}-header dpzvc3-1px-bottom`;
  const contentCls = `${prefixCls}-content`;
  const footerCls = `${prefixCls}-footer dpzvc3-1px-top`;

  return (
    <div className={classes} style={{ width }}>
      <div className={headerCls}>{header}</div>
      <div className={contentCls}>{children}</div>
      <div className={footerCls}>{footer}</div>
    </div>
  );
};

export type { cardProps } from './types';
export default Card;
