// src/views/Badge/Badge.tsx
import { defineComponent } from 'vue'
import './Badge.less'
import Badge from '@/components/badge/index'

export default defineComponent({
  name: 'ViewBadge',
  setup() {
    return () => (
      <div class="Badge">
        <Badge size="sss" number="10">
          <div class="item" />
        </Badge>
        <Badge number="100" max={99} dot={false}>
          <div class="item" />
        </Badge>
        <Badge number="100" max={99} dot={true}>
          <div class="item" />
        </Badge>
      </div>
    )
  }
})

// apps/views-react/src/views/Badge.tsx
import React from 'react';
import { Badge } from '@dpzvc3/react';
import './Badge.css';

const ViewBadge: React.FC = () => {
  return (
    <div className="Badge">
      <Badge number={10}>
        <div className="item" />
      </Badge>

      <Badge number={100} max={99} dot={false}>
        <div className="item" />
      </Badge>

      <Badge number={100} max={99} dot={true}>
        <div className="item" />
      </Badge>
    </div>
  );
};

export default ViewBadge;
