// src/views/Popup.vue
<template>
  <div class="Popup">
    <VButton
      width="50%"
      @click="() => showPop('top')"
    >
      Top
    </VButton>
    <VButton
      width="50%"
      @click="() => showPop('right')"
    >
      Right
    </VButton>
    <VButton
      width="50%"
      @click="() => showPop('bottom')"
    >
      Bottom
    </VButton>
    <VButton
      width="50%"
      @click="() => showPop('left')"
    >
      Left
    </VButton>

    <Popup
      v-model="show"
      :position="side"
      :width="width"
      :height="height"
      :show-mask="true"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, nextTick } from 'vue'
// import type { Side } from './dist/types/components/popup/types'
import type { PopupProps } from '@/components/popup/types'
type Side = 'top' | 'right' | 'bottom' | 'left'

export default defineComponent({
  name: 'ViewPopup',
  setup () {
    const side = ref<PopupProps['position']>('top')
    const show = ref<PopupProps['modelValue']>(false)
    const width = ref<PopupProps['width']>('100%')
    const height = ref<PopupProps['height']>('100%')
    const sideList: Side[] = ['top', 'right', 'bottom', 'left']

    const showPop = (s: Side) => {
      show.value = false
      nextTick(() => {
        if (!sideList.includes(s)) s = 'top'

        switch (s) {
        case 'top':
          width.value = '100%'
          height.value = 0
          break
        case 'right':
          width.value = '70%'
          height.value = '100%'
          break
        case 'bottom':
          width.value = '100%'
          height.value = '70%'
          break
        case 'left':
          width.value = '70%'
          height.value = '100%'
          break
        }

        side.value = s

        setTimeout(() => {
          show.value = true
        }, 350)
      })
    }

    return {
      side,
      show,
      width,
      height,
      showPop
    }
  }
})
</script>

<style scoped>
.Popup {
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  align-items: center;
}
</style>

// apps/views-react/src/views/Popup.tsx
import React, { useState } from 'react'
import type { CSSProperties } from 'react'
// import Popup from '@/components/popup'
import { Popup } from '@dpzvc3/react' // 如果发布包可直接用 '@dpzvc3/react'
import type { PopupProps } from '@dpzvc3/react'
import './popup.css';

type Side = 'top' | 'right' | 'bottom' | 'left'

const sideList: Side[] = ['top', 'right', 'bottom', 'left']

const ViewPopup: React.FC = () => {
  const [side, setSide] = useState<PopupProps['position']>('top')
  const [show, setShow] = useState<PopupProps['modelValue']>(false)
  const [width, setWidth] = useState<PopupProps['width']>('100%')
  const [height, setHeight] = useState<PopupProps['height']>('100%')

  const showPop = (s: Side) => {
    // 先关闭，保证重新触发动画
    setShow(false)

    // React 不需要 nextTick，用微任务即可
    Promise.resolve().then(() => {
      if (!sideList.includes(s)) s = 'top'

      switch (s) {
        case 'top':
          setWidth('100%')
          setHeight('70%')
          break
        case 'right':
          setWidth('70%')
          setHeight('100%')
          break
        case 'bottom':
          setWidth('100%')
          setHeight('70%')
          break
        case 'left':
          setWidth('70%')
          setHeight('100%')
          break
      }

      setSide(s)

      // 等上一次关闭动画结束
      setTimeout(() => {
        setShow(true)
      }, 350)
    })
  }

  return (
    <div className="Popup">
      <button width="50%" onClick={() => showPop('top')}>
        Top
      </button>
      <button width="50%" onClick={() => showPop('right')}>
        Right
      </button>
      <button width="50%" onClick={() => showPop('bottom')}>
        Bottom
      </button>
      <button width="50%" onClick={() => showPop('left')}>
        Left
      </button>

      <Popup
        modelValue={show}
        position={side}
        width={width}
        height={height}
        showMask={true}
        onUpdateModelValue={setShow}
      />
    </div>
  )
}

export default ViewPopup
