// packages/react/src/components/Popup/index.tsx
import React, { useEffect, useRef, useState } from 'react';
import type { PopupProps } from './types';
import { CSSTransition } from 'react-transition-group';
import '@dpzvc3/styles/dist/components/popup.css';
import '@dpzvc3/styles/dist/utils/animation.css';

const prefixCls = 'dpzvc3-popup';

const Popup: React.FC<PopupProps> = (props) => {
  const {
    modelValue = false,
    position = 'bottom',
    showMask = true,
    maskClosable = true,
    width = '100%',
    height,
    styles = {},
    children,
    onUpdateModelValue,
  } = props;

  const [visible, setVisible] = useState<boolean>(!!modelValue);
  const [mask, setMask] = useState<boolean>(!!showMask);

  const maskRef = useRef<HTMLDivElement | null>(null);
  const contentRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => setVisible(!!modelValue), [modelValue]);
  useEffect(() => setMask(!!showMask), [showMask]);

  // notify parent (simulate update:modelValue)
  useEffect(() => {
    if (typeof onUpdateModelValue === 'function') onUpdateModelValue(visible);
  }, [visible]);

  const close = () => {
    if (maskClosable && mask) setVisible(false);
  };

  const contentStyle: React.CSSProperties = {
    ...styles,
    width,
    height: height !== null ? height : position === 'top' ? 'auto' : '100%',
  };

  return (
    <div className={prefixCls}>
      <CSSTransition
        nodeRef={maskRef}
        in={mask && visible}
        timeout={300}
        classNames="dpzvc3-ani-fade"
        mountOnEnter
        unmountOnExit
      >
        <div
          ref={maskRef}
          className={`${prefixCls}-mask`}
          onClick={close}
          onTouchMove={(e) => e.preventDefault()}
        />
      </CSSTransition>

      <CSSTransition
        nodeRef={contentRef}
        in={visible}
        timeout={300}
        classNames={`dpzvc3-ani-${position}`}
        mountOnEnter
        unmountOnExit
      >
        <div
          ref={contentRef}
          className={`${prefixCls}-${position} ${prefixCls}-content`}
          style={contentStyle}
        >
          {children}
        </div>
      </CSSTransition>
    </div>
  );
};

export type { PopupProps } from './types';
export default Popup;

// src/components/popup/popup.vue
<template>
  <div :class="classes">
    <transition name="dpzvc3-ani-fade">
      <div
        v-if="mask && visible"
        class="dpzvc3-popup-mask"
        @click="close"
        @touchmove.prevent
      />
    </transition>
    <transition :name="'dpzvc3-ani-' + position">
      <div
        v-if="visible"
        :class="popupClasses"
        :style="contentStyle"
      >
        <slot />
      </div>
    </transition>
  </div>
</template>

<script>
import { ref, computed, watch } from 'vue'

const prefixCls = 'dpzvc3-popup'

export default {
  name: 'Dpzvc3Popup',
  props: {
    modelValue: { // Vue 3 v-model 默认绑定
      type: Boolean,
      default: false
    },
    position: {
      type: String,
      default: 'bottom',
      validator: (val) => ['top', 'bottom', 'center'].includes(val)
    },
    showMask: {
      type: Boolean,
      default: true
    },
    maskClosable: {
      type: Boolean,
      default: true
    },
    width: {
      type: [Number, String],
      default: '100%'
    },
    height: {
      type: [Number, String]
    },
    styles: {
      type: Object,
      default: () => ({})
    }
  },
  setup (props, { emit }) {
    const visible = ref(props.modelValue)
    const mask = ref(props.showMask)

    // 同步 props -> 状态
    watch(() => props.modelValue, (val) => { visible.value = val })
    watch(visible, (val) => { emit('update:modelValue', val) })

    watch(() => props.showMask, (val) => { mask.value = val })

    const classes = computed(() => [prefixCls])
    const popupClasses = computed(() => [`${prefixCls}-${props.position}`, `${prefixCls}-content`])
    const contentStyle = computed(() => {
      const heightValue = props.height != null ? props.height : (props.position === 'top' ? 'auto' : '100%')
      return { ...props.styles, width: props.width, height: heightValue }
    })

    const close = () => {
      if (props.maskClosable && mask.value) visible.value = false
    }

    return {
      visible,
      mask,
      classes,
      popupClasses,
      contentStyle,
      close
    }
  }
}
</script>
