// packages/react/src/components/card/index.tsx
import React from 'react';
import type { cardProps } from './types';
import '@dpzvc3/styles/dist/components/card.css';

const prefixCls = 'dpzvc3-card';

const Card: React.FC<cardProps> = (props) => {
  const { width = '100%', header, footer, children } = props;

  const classes = [prefixCls].join(' ');
  const headerCls = `${prefixCls}-header dpzvc3-1px-bottom`;
  const contentCls = `${prefixCls}-content`;
  const footerCls = `${prefixCls}-footer dpzvc3-1px-top`;

  return (
    <div className={classes} style={{ width }}>
      <div className={headerCls}>{header}</div>
      <div className={contentCls}>{children}</div>
      <div className={footerCls}>{footer}</div>
    </div>
  );
};

export type { cardProps } from './types';
export default Card;

// src/components/card/card.vue
<template>
  <div
    :class="classes"
    :style="{ width: cardWidth }"
  >
    <div :class="headerClass">
      <slot name="header" />
    </div>
    <div :class="contentClass">
      <slot>
        <div class="main" />
      </slot>
    </div>
    <div :class="footerClass">
      <slot name="footer" />
    </div>
  </div>
</template>

<script>
import { defineComponent, computed } from 'vue'

const prefixCls = 'dpzvc3-card'

export default defineComponent({
  name: 'Dpzvc3Card',
  props: {
    width: {
      type: String,
      default: '100%'
    }
  },
  setup (props) {
    const classes = computed(() => [prefixCls])
    const headerClass = computed(() => [`${prefixCls}-header`, 'dpzvc3-1px-bottom'])
    const contentClass = computed(() => [`${prefixCls}-content`])
    const footerClass = computed(() => [`${prefixCls}-footer`, 'dpzvc3-1px-top'])
    const cardWidth = computed(() => props.width)
    return {
      classes,
      headerClass,
      contentClass,
      footerClass,
      cardWidth
      // 不返回 width，模板直接用 props.width
    }
  }
})
</script>
