// packages/react/src/stories/Badge.tsx
import React from 'react';
import { Badge } from '@dpzvc3/react';
import '@dpzvc3/styles/dist/components/badge.css';

export default {
  title: 'Badge',
  component: Badge,
};

export const Basic = () => (
  <div style={{ display: 'flex', gap: 20 }}>
    <Badge number={10}>
      <div style={{ width: 45, height: 45, backgroundColor: 'red' }} />
    </Badge>
    <Badge number={100} max={99} dot={false}>
      <div style={{ width: 45, height: 45, backgroundColor: 'red' }} />
    </Badge>
    <Badge number={100} max={99} dot>
      <div style={{ width: 45, height: 45, backgroundColor: 'red' }} />
    </Badge>
  </div>
);

// src/views/Badge.vue
<template>
  <div class="Badge">
    <Badge
      number="10"
    >
      <div class="item" />
    </Badge>

    <Badge
      number="100"
      :max="99"
      :dot="false"
    >
      <div class="item" />
    </Badge>

    <Badge
      number="100"
      :max="99"
      :dot="true"
    >
      <div class="item" />
    </Badge>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
// import Badge from '@/components/badge/badge.vue' // 修改为你实际路径

export default defineComponent({
  name: 'ViewBadge',
  setup () {
    // 这个组件不需要响应式数据，所以 setup 可以为空
    return {}
  }
})
</script>

<style lang="less" scoped>
.Badge {
  width: 100%;
  margin-top: 100px;
  display: flex;
  justify-content: space-around;

  .item {
    width: 45px;
    height: 45px;
    background-color: red;
  }
}
</style>
