// src/components/popup/popup.tsx
import {
  defineComponent,
  ref,
  computed,
  watch,
  PropType,
  Transition,
} from "vue";
import { inputEmits } from "./types";
import type { CSSProperties } from "vue";
import type { PopupProps, PopupEmits, PopupClassNameArray } from "./types";
export type { PopupProps, PopupEmits };

const prefixCls = "dpzvc3-popup";

export default defineComponent({
  name: "Dpzvc3Popup",
  props: {
    modelValue: { type: Boolean, default: false },
    position: {
      type: String as PropType<PopupProps["position"]>,
      default: "bottom",
    },
    showMask: { type: Boolean, default: true },
    maskClosable: { type: Boolean, default: true },
    width: {
      type: [Number, String] as PropType<number | string>,
      default: "100%",
    },
    height: { type: [Number, String] as PropType<number | string> },
    styles: {
      type: Object as PropType<PopupProps["styles"]>,
      default: () => ({}),
    },
  },
  emits: inputEmits,
  setup(props, { emit, slots }) {
    const visible = ref<PopupProps["modelValue"]>(props.modelValue);
    const mask = ref<PopupProps["showMask"]>(props.showMask);

    watch<PopupProps["modelValue"]>(
      () => props.modelValue,
      (val) => {
        visible.value = val;
      },
    );
    watch<PopupProps["modelValue"]>(visible, (val) => {
      emit("update:modelValue", val);
    });
    watch<PopupProps["showMask"]>(
      () => props.showMask,
      (val) => {
        mask.value = val;
      },
    );

    const classes = computed<PopupClassNameArray>(() => [prefixCls]);
    const popupClasses = computed<PopupClassNameArray>(() => [
      `${prefixCls}-${props.position}`,
      `${prefixCls}-content`,
    ]);
    const contentStyle = computed<CSSProperties>(() => {
      const heightValue =
        props.height !== null
          ? props.height
          : props.position === "top"
            ? "auto"
            : "100%";
      return { ...props.styles, width: props.width, height: heightValue };
    });

    const close = () => {
      if (props.maskClosable && mask.value) visible.value = false;
    };

    return () => (
      <div class={classes.value}>
        {/* 遮罩层 */}
        <Transition
          name="dpzvc3-ani-fade"
          v-slots={{
            default: () =>
              mask.value &&
              visible.value && (
                <div
                  class={`${prefixCls}-mask`}
                  onClick={close}
                  onTouchMove={(e: any) => e.preventDefault()}
                />
              ),
          }}
        />

        {/* 弹窗内容 */}
        <Transition
          name={`dpzvc3-ani-${props.position}`}
          v-slots={{
            default: () =>
              visible.value && (
                <div class={popupClasses.value} style={contentStyle.value}>
                  {slots.default?.()}
                </div>
              ),
          }}
        />
      </div>
    );
  },
});

// packages/react/src/components/Popup/index.tsx
import React, { useEffect, useRef, useState } from 'react';
import type { PopupProps } from './types';
import { CSSTransition } from 'react-transition-group';
import '@dpzvc3/styles/dist/components/popup.css';
import '@dpzvc3/styles/dist/utils/animation.css';

const prefixCls = 'dpzvc3-popup';

const Popup: React.FC<PopupProps> = (props) => {
  const {
    modelValue = false,
    position = 'bottom',
    showMask = true,
    maskClosable = true,
    width = '100%',
    height,
    styles = {},
    children,
    onUpdateModelValue,
  } = props;

  const [visible, setVisible] = useState<boolean>(!!modelValue);
  const [mask, setMask] = useState<boolean>(!!showMask);

  const maskRef = useRef<HTMLDivElement | null>(null);
  const contentRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => setVisible(!!modelValue), [modelValue]);
  useEffect(() => setMask(!!showMask), [showMask]);

  // notify parent (simulate update:modelValue)
  useEffect(() => {
    if (typeof onUpdateModelValue === 'function') onUpdateModelValue(visible);
  }, [visible]);

  const close = () => {
    if (maskClosable && mask) setVisible(false);
  };

  const contentStyle: React.CSSProperties = {
    ...styles,
    width,
    height: height !== null ? height : position === 'top' ? 'auto' : '100%',
  };

  return (
    <div className={prefixCls}>
      <CSSTransition
        nodeRef={maskRef}
        in={mask && visible}
        timeout={300}
        classNames="dpzvc3-ani-fade"
        mountOnEnter
        unmountOnExit
      >
        <div
          ref={maskRef}
          className={`${prefixCls}-mask`}
          onClick={close}
          onTouchMove={(e) => e.preventDefault()}
        />
      </CSSTransition>

      <CSSTransition
        nodeRef={contentRef}
        in={visible}
        timeout={300}
        classNames={`dpzvc3-ani-${position}`}
        mountOnEnter
        unmountOnExit
      >
        <div
          ref={contentRef}
          className={`${prefixCls}-${position} ${prefixCls}-content`}
          style={contentStyle}
        >
          {children}
        </div>
      </CSSTransition>
    </div>
  );
};

export type { PopupProps } from './types';
export default Popup;
