// src/components/action-sheet/actionSheet.vue
<template>
  <div>
    <Popup
      v-model="visible"
      position="bottom"
      :styles="{ background: 'transparent' }"
    >
      <div :class="classes">
        <ul :class="wrapperClasses">
          <li
            v-for="(item, key) in actions"
            :key="key"
            :class="wrapperActionClass"
            @click="emit(item, key)"
          >
            <span>{{ item.text }}</span>
          </li>
        </ul>
        <a
          v-if="cancleText"
          href="javascript:;"
          :class="cancleClass"
          @click="visible = false"
        >{{ cancleText }}</a>
      </div>
    </Popup>
  </div>
</template>

<script>
import { ref, computed, watch } from 'vue'
import Popup from '../popup'

const prefixCls = 'dpzvc3-actionSheet'

export default {
  name: 'ActionSheet',
  components: { Popup },
  props: {
    modelValue: { // Vue 3 v-model 默认绑定 modelValue
      type: Boolean,
      default: false
    },
    items: {
      type: Array,
      default: () => []
    },
    cancleText: {
      type: String,
      default: '取消'
    }
  },
  setup (props, { emit }) {
    // 内部状态
    const visible = ref(props.modelValue)
    const actions = ref(props.items)

    // 同步 props.modelValue
    watch(() => props.modelValue, (val) => {
      visible.value = val
    })

    // 监听 visible 改变，通知父组件
    watch(visible, (val) => {
      emit('update:modelValue', val)
    })

    // 样式类
    const classes = computed(() => [prefixCls])
    const wrapperClasses = computed(() => [`${prefixCls}-wrapper`])
    const wrapperActionClass = computed(() => [`${prefixCls}-wrapper-action`])
    const cancleClass = computed(() => [`${prefixCls}-cancle`])

    // 点击事件
    const emitAction = (item, index) => {
      if (item.onClick && typeof item.onClick === 'function') {
        item.onClick(item, index)
      }
      visible.value = false
    }

    return {
      visible,
      actions,
      classes,
      wrapperClasses,
      wrapperActionClass,
      cancleClass,
      emit: emitAction
    }
  }
}
</script>

// packages/react/src/components/action-sheet/index.tsx
import React, { useEffect, useState, useMemo } from 'react';
import type { action_sheetProps, ActionItem } from './types';
import Popup from '../Popup';
import '@dpzvc3/styles/dist/components/action-sheet.css';

const prefixCls = 'dpzvc3-actionSheet';

const ActionSheet: React.FC<action_sheetProps> = (props) => {
  const {
    modelValue = false,
    items = [],
    cancleText = '取消',
    onUpdateModelValue,
  } = props;

  const [visible, setVisible] = useState<boolean>(modelValue);
  const [actions, setActions] = useState<ActionItem[]>(items);

  useEffect(() => {
    console.log('modelValue changed:', modelValue);
    setVisible(modelValue);
  }, [modelValue]);

  useEffect(() => {
    setActions(items);
  }, [items]);

  const classes = useMemo(() => prefixCls, []);
  const wrapperClasses = useMemo(() => `${prefixCls}-wrapper`, []);
  const wrapperActionClass = useMemo(() => `${prefixCls}-wrapper-action`, []);
  const cancleClass = useMemo(() => `${prefixCls}-cancle`, []);

  const emitAction = (item: ActionItem, index: number) => {
    item.onClick?.(item, index);
    handleClose();
  };

  const handleClose = () => {
    console.log('Closing ActionSheet');
    setVisible(false);
    onUpdateModelValue && onUpdateModelValue(false);
  };

  return (
    <Popup
      modelValue={visible}
      position="bottom"
      maskClosable={false}
      styles={{ background: 'transparent' }}
      onUpdateModelValue={(v) => {
        console.log('Popup visibility changed:', v);
        setVisible(v);
        onUpdateModelValue && onUpdateModelValue(v);
      }}
    >
      <div className={classes}>
        <ul className={wrapperClasses}>
          {actions.map((item, index) => (
            <li
              key={index}
              className={wrapperActionClass}
              onClick={() => emitAction(item, index)}
            >
              <span>{item.text}</span>
            </li>
          ))}
        </ul>
        {cancleText && (
          <a href="javascript:;" className={cancleClass} onClick={handleClose}>
            {cancleText}
          </a>
        )}
      </div>
      {props.children}
    </Popup>
  );
};

export type { action_sheetProps, ActionItem } from './types';
export default ActionSheet;
