// src/components/button/button.vue
<template>
  <div :class="classes" :style="wrapperStyles">
    <button :style="styles" :class="buttonClass" :disabled="disabled" @click.stop="handleClick">
      <slot name="left">
        <span v-show="loadingValue" class="loading">
          <Spinner type="blade" size="15" color="#ffffff" />
        </span>
      </slot>
      <slot><span>确定</span></slot>
      <slot name="right" />
    </button>
  </div>
</template>

<script>
import { defineComponent, computed } from 'vue'
import Spinner from '../spinner'

const prefixCls = 'dpzvc3-button'

export default defineComponent({
  name: 'VButton',
  components: { Spinner },
  props: {
    type: {
      type: String,
      default: 'normal',
      validator: (val) =>
        ['success', 'loading', 'normal', 'primary', 'warning', 'danger', 'text'].includes(val)
    },
    styles: {
      type: Object,
      default: () => ({})
    },
    circle: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    inline: { type: Boolean, default: false },
    width: { type: String, default: '100%' },
    height: { type: String, default: '40px' },
    loading: { type: Boolean, default: false },
    radius: { type: Boolean, default: true },
    border: { type: String, default: 'all' }
  },
  setup (props, { emit }) {
    // 外层容器类
    const classes = computed(() => [
      prefixCls,
      {
        [`${prefixCls}-circle`]: props.circle,
        [`${prefixCls}-inline`]: props.inline
      }
    ])

    // 外层容器样式
    const wrapperStyles = computed(() => ({
      display: props.inline ? 'inline-block' : 'block',
      width: props.width,
      height: props.height
    }))

    // button 类
    const buttonClass = computed(() => [
      `${prefixCls}-btn`,
      [`dpzvc3-1px-${props.border}`],
      {
        [`${prefixCls}-success`]: props.type === 'success',
        [`${prefixCls}-loading`]: props.type === 'loading',
        [`${prefixCls}-normal`]: props.type === 'normal',
        [`${prefixCls}-warning`]: props.type === 'warning',
        [`${prefixCls}-danger`]: props.type === 'danger',
        [`${prefixCls}-text`]: props.type === 'text',
        [`${prefixCls}-primary`]: props.type === 'primary',
        [`${prefixCls}-disabled`]: props.disabled,
        [`${prefixCls}-radius`]: props.radius
      }
    ])

    // 点击事件
    const handleClick = (e) => {
      if (props.disabled || props.loading) return
      emit('click', e)
    }

    // 状态
    const loadingValue = computed(() => props.loading)

    return {
      classes,
      wrapperStyles,
      buttonClass,
      handleClick,
      loadingValue
    }
  }
})
</script>

// packages/react/src/components/Button/index.tsx
import React, { useMemo } from 'react';
import type { ButtonProps } from './types';
import Spinner from '../Spinner';
import '@dpzvc3/styles/dist/components/dp-button.css';

const prefixCls = 'dpzvc3-button';

const Button: React.FC<ButtonProps> = ({
  type = 'normal',
  styles = {},
  circle = false,
  disabled = false,
  inline = false,
  width = '100%',
  height = '40px',
  loading = false,
  radius = true,
  border = 'all',
  left,
  right,
  children,
  onClick,
}) => {
  const wrapperStyle: React.CSSProperties = useMemo(
    () => ({
      display: inline ? 'inline-block' : 'block',
      width,
      height,
    }),
    [inline, width, height]
  );

  const wrapperCls = useMemo(() => {
    const cls = [prefixCls];
    if (circle) cls.push(`${prefixCls}-circle`);
    if (inline) cls.push(`${prefixCls}-inline`);
    return cls.join(' ');
  }, [circle, inline]);

  const btnClass = useMemo(() => {
    const classes: string[] = [`${prefixCls}-btn`, `dpzvc3-1px-${border}`];
    classes.push(`${prefixCls}-${type}`);
    if (disabled) classes.push(`${prefixCls}-disabled`);
    if (radius) classes.push(`${prefixCls}-radius`);
    return classes.join(' ');
  }, [type, border, disabled, radius]);

  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    if (disabled || loading) return;
    onClick && onClick(e);
  };

  return (
    <div className={wrapperCls} style={wrapperStyle}>
      <button
        className={btnClass}
        style={styles}
        disabled={disabled}
        onClick={handleClick}
      >
        {/* left slot or loading */}
        {left
          ? left
          : loading && (
              <span className="loading">
                <Spinner type="blade" size={15} color="#ffffff" />
              </span>
            )}

        {/* default slot */}
        {children ? children : <span>确定</span>}

        {/* right slot */}
        {right}
      </button>
    </div>
  );
};

export type { ButtonProps } from './types';
export default Button;
